name: fnb_business_case
version: 1.0.0
config-version: 2

profile: demo_postgres

model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
macro-paths: [macros]
snapshot-paths: [snapshots]

target-path: target
clean-targets:
  - target
  - dbt_modules

quoting:
  identifier: false