demo_postgres:
  target: loc
  outputs:
    loc:
      type: postgres
      host: postgres
      user: fnb
      password: S3cret
      port: 5432
      dbname: fnb_demo
      schema: insight
      threads: 4
      connect_timeout: 10 # default 10 seconds
  